<?php

// Pastikan autoload dari Composer sudah benar
require __DIR__ . '/vendor/autoload.php';

// HTML sederhana untuk PDF
$html = "<html><body><h1>Test PDF</h1><p>This is a simple test PDF generated by mPDF.</p></body></html>";

// Membuat objek mPDF
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML($html);

// Menyimpan PDF ke file
$mpdf->Output(__DIR__ . '/test_order_report.pdf', 'F'); // Menyimpan ke file test_order_report.pdf

echo "PDF generated!";
